// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDyu2rClid9Jl277JZin7OFJf2MOw9nXw0',
//     appId: '1:137436429211:android:011bbcf0fdb70ea5697f3e',
//     messagingSenderId: '273578508477',
//     projectId: 'mpapp-22134',
//     authDomain: 'mpapp-22134.firebaseapp.com',
//     storageBucket: 'mpapp-22134.firebasestorage.app',
//     measurementId: 'G-1XXCG5HMQC',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAocZm7LuApLOORQ9UJ08AxzBydQ8BgDIE',
//     appId: '1:273578508477:android:b6374af98d088df5a2f7d4',
//     messagingSenderId: '273578508477',
//     projectId: 'mpapp-22134',
//     storageBucket: 'mpapp-22134.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDPlKFgIwe0X_P7EDB0PNS8XfQ1DCnUBe8',
//     appId: '1:273578508477:ios:4bb265710fe65aa0a2f7d4',
//     messagingSenderId: '273578508477',
//     projectId: 'mpapp-22134',
//     storageBucket: 'mpapp-22134.firebasestorage.app',
//     iosBundleId: 'com.example.mantriApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDPlKFgIwe0X_P7EDB0PNS8XfQ1DCnUBe8',
//     appId: '1:273578508477:ios:4bb265710fe65aa0a2f7d4',
//     messagingSenderId: '273578508477',
//     projectId: 'mpapp-22134',
//     storageBucket: 'mpapp-22134.firebasestorage.app',
//     iosBundleId: 'com.example.mantriApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDyu2rClid9Jl277JZin7OFJf2MOw9nXw0',
//     appId: '1:273578508477:web:011cd2a4ce4c8a52a2f7d4',
//     messagingSenderId: '273578508477',
//     projectId: 'mpapp-22134',
//     authDomain: 'mpapp-22134.firebaseapp.com',
//     storageBucket: 'mpapp-22134.firebasestorage.app',
//     measurementId: 'G-XR4CD0RNWM',
//   );
// }
