class StatesCitiesData {
  static const Map<String, List<String>> stateCityMap = {
    'Andaman and Nicobar Islands': [
      'Port Blair',
      'Diglipur',
      'Mayabunder',
      'Rangat',
      'Havelock Island',
    ],
    'Andhra Pradesh': [
      'Visakhapatnam',
      'Vijayawada',
      'Guntur',
      'Nellore',
      'Kurnool',
      'Kakinada',
      'Tirupati',
      'Rajahmundry',
      'Kadapa',
      'Anantapur',
      'Eluru',
      'Vizianagaram',
      'Chittoor',
      'Machilipatnam',
      'Ongole',
      'Adoni',
      'Tenali',
      'Proddatur',
      'Hindupur',
      'Bhimavaram',
    ],
    'Arunachal Pradesh': [
      'Itanagar',
      'Naharlagun',
      'Pasighat',
      'Roing',
      'Tawang',
      'Ziro',
      'Bomdila',
      'Tezu',
      'Aalo',
    ],
    'Assam': [
      'Guwahati',
      'Silchar',
      'Dibrugarh',
      'Jorhat',
      'Nagaon',
      'Tinsukia',
      'Tezpur',
      'Bongaigaon',
      'Dhubri',
      'Diphu',
      'North Lakhimpur',
      'Karimganj',
      'Sibsagar',
      'Goalpara',
      'Barpeta',
    ],
    'Bihar': [
      'Patna',
      'Gaya',
      'Bhagalpur',
      'Muzaffarpur',
      'Purnia',
      'Darbhanga',
      'Bihar Sharif',
      'Arrah',
      'Begusarai',
      'Katihar',
      'Munger',
      'Chhapra',
      'Danapur',
      'Bettiah',
      'Saharsa',
      'Sasaram',
      'Hajipur',
      'Dehri',
      'Siwan',
      'Motihari',
    ],
    'Chandigarh': ['Chandigarh'],
    'Chhattisgarh': [
      'Raipur',
      'Bhilai',
      'Bilaspur',
      'Korba',
      'Rajnandgaon',
      'Raigarh',
      'Jagdalpur',
      'Ambikapur',
      'Dhamtari',
      'Mahasamund',
      'Champa',
      'Durg',
    ],
    'Dadra and Nagar Haveli and Daman and Diu': [
      'Daman',
      'Diu',
      'Silvassa',
      'Amli',
    ],
    'Delhi': [
      'New Delhi',
      'Delhi',
      'Noida',
      'Gurugram',
      'Faridabad',
      'Ghaziabad',
    ],
    'Goa': [
      'Panaji',
      'Margao',
      'Vasco da Gama',
      'Mapusa',
      'Ponda',
      'Bicholim',
      'Curchorem',
    ],
    'Gujarat': [
      'Ahmedabad',
      'Surat',
      'Vadodara',
      'Rajkot',
      'Bhavnagar',
      'Jamnagar',
      'Junagadh',
      'Gandhidham',
      'Nadiad',
      'Gandhinagar',
      'Anand',
      'Morbi',
      'Mehsana',
      'Surendranagar',
      'Bharuch',
      'Vapi',
      'Navsari',
      'Veraval',
      'Porbandar',
      'Godhra',
    ],
    'Haryana': [
      'Faridabad',
      'Gurgaon',
      'Panipat',
      'Ambala',
      'Yamunanagar',
      'Rohtak',
      'Hisar',
      'Karnal',
      'Sonipat',
      'Panchkula',
      'Sirsa',
      'Bhiwani',
      'Bahadurgarh',
      'Jind',
      'Thanesar',
      'Kaithal',
      'Rewari',
      'Palwal',
    ],
    'Himachal Pradesh': [
      'Shimla',
      'Mandi',
      'Dharamshala',
      'Solan',
      'Palampur',
      'Baddi',
      'Nahan',
      'Paonta Sahib',
      'Una',
      'Kullu',
      'Hamirpur',
      'Bilaspur',
      'Chamba',
    ],
    'Jammu and Kashmir': [
      'Srinagar',
      'Jammu',
      'Anantnag',
      'Baramulla',
      'Kathua',
      'Sopore',
      'Samba',
      'Udhampur',
      'Rajouri',
      'Poonch',
      'Kupwara',
      'Pulwama',
    ],
    'Jharkhand': [
      'Ranchi',
      'Jamshedpur',
      'Dhanbad',
      'Bokaro Steel City',
      'Deoghar',
      'Phusro',
      'Hazaribagh',
      'Giridih',
      'Ramgarh',
      'Medininagar',
      'Chas',
      'Adityapur',
      'Gumla',
      'Dumka',
      'Chaibasa',
    ],
    'Karnataka': [
      'Bengaluru',
      'Mysuru',
      'Hubballi-Dharwad',
      'Mangaluru',
      'Belagavi',
      'Kalaburagi',
      'Davanagere',
      'Ballari',
      'Vijayapura',
      'Shivamogga',
      'Tumakuru',
      'Raichur',
      'Bidar',
      'Hosapete',
      'Gadag-Betageri',
      'Hassan',
      'Udupi',
      'Bhadravati',
      'Robertsonpet',
      'Chitradurga',
    ],
    'Kerala': [
      'Thiruvananthapuram',
      'Kochi',
      'Kozhikode',
      'Kollam',
      'Thrissur',
      'Alappuzha',
      'Palakkad',
      'Malappuram',
      'Manjeri',
      'Thalassery',
      'Ponnani',
      'Vatakara',
      'Kanhangad',
      'Kottayam',
      'Kannur',
    ],
    'Ladakh': ['Leh', 'Kargil'],
    'Lakshadweep': ['Kavaratti', 'Agatti', 'Andrott', 'Minicoy'],
    'Madhya Pradesh': [
      'Indore',
      'Bhopal',
      'Jabalpur',
      'Gwalior',
      'Ujjain',
      'Sagar',
      'Dewas',
      'Satna',
      'Ratlam',
      'Rewa',
      'Katni',
      'Singrauli',
      'Burhanpur',
      'Khandwa',
      'Bhind',
      'Chhindwara',
      'Guna',
      'Shivpuri',
      'Vidisha',
      'Damoh',
    ],
    'Maharashtra': [
      'Mumbai',
      'Pune',
      'Nagpur',
      'Thane',
      'Nashik',
      'Kalyan-Dombivli',
      'Vasai-Virar',
      'Aurangabad',
      'Navi Mumbai',
      'Solapur',
      'Mira-Bhayandar',
      'Amravati',
      'Nagpur',
      'Akola',
      'Bhiwandi-Nizampur',
      'Ahmednagar',
      'Jalgaon',
      'Kolhapur',
      'Sangli-Miraj & Kupwad',
      'Malegaon',
      'Dhule',
      'Satara',
      'Ratnagiri',
      'Beed',
      'Chandrapur',
      'Parbhani',
      'Latur',
      'Gondia',
      'Wardha',
      'Yavatmal',
      'Nanded',
      'Buldhana',
      'Washim',
      'Gadchiroli',
      'Bhandara',
      'Raigad',
      'Sindhudurg',
      'Osmanabad',
      'Nandurbar',
      'Hingoli',
    ],
    'Manipur': [
      'Imphal',
      'Thoubal',
      'Bishnupur',
      'Churachandpur',
      'Senapati',
      'Ukhrul',
    ],
    'Meghalaya': [
      'Shillong',
      'Tura',
      'Jowai',
      'Nongpoh',
      'Williamnagar',
      'Baghmara',
    ],
    'Mizoram': [
      'Aizawl',
      'Lunglei',
      'Saiha',
      'Champhai',
      'Kolasib',
      'Serchhip',
    ],
    'Nagaland': [
      'Dimapur',
      'Kohima',
      'Mokokchung',
      'Tuensang',
      'Wokha',
      'Zunheboto',
      'Mon',
      'Phek',
    ],
    'Odisha': [
      'Bhubaneswar',
      'Cuttack',
      'Rourkela',
      'Berhampur',
      'Sambalpur',
      'Puri',
      'Balasore',
      'Bhadrak',
      'Baripada',
      'Jharsuguda',
      'Jeypore',
      'Anugul',
      'Keonjhar',
      'Rayagada',
      'Dhenkanal',
    ],
    'Puducherry': ['Puducherry', 'Oulgaret', 'Karaikal', 'Mahe', 'Yanam'],
    'Punjab': [
      'Ludhiana',
      'Amritsar',
      'Jalandhar',
      'Patiala',
      'Bathinda',
      'Mohali',
      'Hoshiarpur',
      'Batala',
      'Pathankot',
      'Moga',
      'Abohar',
      'Malerkotla',
      'Khanna',
      'Muktsar',
      'Barnala',
      'Firozpur',
      'Kapurthala',
      'Phagwara',
    ],
    'Rajasthan': [
      'Jaipur',
      'Jodhpur',
      'Kota',
      'Bikaner',
      'Ajmer',
      'Udaipur',
      'Bhilwara',
      'Alwar',
      'Bharatpur',
      'Sikar',
      'Sri Ganganagar',
      'Pali',
      'Chittorgarh',
      'Bundee',
      'Jhalawar',
      'Jaisalmer',
      'Nagaur',
      'Barmer',
      'Hanumangarh',
      'Tonk',
    ],
    'Sikkim': ['Gangtok', 'Namchi', 'Gyalshing', 'Mangan', 'Singtam'],
    'Tamil Nadu': [
      'Chennai',
      'Coimbatore',
      'Madurai',
      'Tiruchirappalli',
      'Salem',
      'Tirunelveli',
      'Tiruppur',
      'Ambattur',
      'Avadi',
      'Tiruvottiyur',
      'Thoothukudi',
      'Nagercoil',
      'Thanjavur',
      'Pallavaram',
      'Dindigul',
      'Vellore',
      'Tambaram',
      'Cuddalore',
      'Kancheepuram',
      'Erode',
    ],
    'Telangana': [
      'Hyderabad',
      'Warangal',
      'Nizamabad',
      'Karimnagar',
      'Ramagundam',
      'Khammam',
      'Mahbubnagar',
      'Nalgonda',
      'Adilabad',
      'Suryapet',
      'Miryalaguda',
      'Siddipet',
      'Jagtial',
      'Mancherial',
      'Kothagudem',
    ],
    'Tripura': ['Agartala', 'Dharmanagar', 'Udaipur', 'Kailasahar', 'Belonia'],
    'Uttar Pradesh': [
      'Lucknow',
      'Kanpur',
      'Ghaziabad',
      'Agra',
      'Meerut',
      'Varanasi',
      'Prayagraj',
      'Bareilly',
      'Aligarh',
      'Moradabad',
      'Saharanpur',
      'Gorakhpur',
      'Noida',
      'Firozabad',
      'Jhansi',
      'Muzaffarnagar',
      'Mathura-Vrindavan',
      'Ayodhya',
      'Rampur',
      'Shahjahanpur',
    ],
    'Uttarakhand': [
      'Dehradun',
      'Haridwar',
      'Roorkee',
      'Haldwani-cum-Kathgodam',
      'Rudrapur',
      'Kashipur',
      'Rishikesh',
      'Nainital',
      'Srinagar',
      'Pithoragarh',
    ],
    'West Bengal': [
      'Kolkata',
      'Howrah',
      'Asansol',
      'Siliguri',
      'Durgapur',
      'Bardhaman',
      'Malda',
      'Baharampur',
      'Habra',
      'Kharagpur',
      'Shantipur',
      'Dankuni',
      'Dhulian',
      'Ranaghat',
      'Haldia',
    ],
  };

  static List<String> get allStates => stateCityMap.keys.toList()..sort();

  static List<String> getCities(String state, {List<dynamic>? customCities}) {
    // We must call .toList() to create a mutable copy before calling .sort()
    final staticCities = stateCityMap[state]?.toList() ?? [];
    if (customCities != null) {
      final dbCities = customCities
          .where((c) => c.state == state)
          .map((c) => c.name as String)
          .toList();
      return {...staticCities, ...dbCities}.toList()..sort();
    }
    return staticCities..sort();
  }

  static List<String> getVillages(String city, {List<dynamic>? customVillages}) {
    if (city.isEmpty) return [];
    List<String> staticVillages = [];
    switch (city) {
      // ── Maharashtra ──────────────────────────────────────────────────────────
      case 'Solapur':
        return [
          'Pandharpur',
          'Bandishegaon',
          'Shelve',
          'Kuroli',
          'Dhondewadi',
          'Upari',
          'Mangalwedha',
          'Akkalkot',
          'Barshi',
          'Mohol',
          'Karmala',
          'Madha',
          'Sangola',
          'Malshiras',
          'Akluj',
          'Natepute',
          'Vairag',
          'Velapur',
          'Kegaon',
          'Hotgi',
          'Nannaj',
          'Bhalwani',
          'Wadala',
          'Chincholi',
          'Dound',
          'Narayanpur',
          'Angar',
          'Kasegaon',
          'Borampuri',
          'Shegaon',
        ];
      case 'Pune':
        return [
          'Wagholi',
          'Hinjawadi',
          'Ambegaon',
          'Manjri',
          'Mulshi',
          'Hadapsar',
          'Koregaon Bhima',
          'Chakan',
          'Loni Kalbhor',
          'Pirangut',
          'Shirur',
          'Indapur',
          'Baramati',
          'Daund',
          'Junnar',
          'Khed',
          'Maval',
          'Purandar',
          'Velhe',
          'Bhor',
          'Uruli Kanchan',
          'Shikrapur',
          'Nighoje',
          'Talegaon Dabhade',
          'Rajgurunagar',
        ];
      case 'Mumbai':
        return [
          'Gorai',
          'Versova',
          'Madh',
          'Manori',
          'Marve',
          'Dharavi',
          'Kanjurmarg',
          'Bhandup',
          'Ghatkopar',
          'Vikhroli',
          'Mulund',
          'Powai',
          'Kurla',
          'Chembur',
          'Govandi',
          'Trombay',
          'Colaba',
          'Worli',
          'Matunga',
          'Sion',
        ];
      case 'Nagpur':
        return [
          'Kamptee',
          'Hingna',
          'Kalmeshwar',
          'Butibori',
          'Wanadongri',
          'Bori',
          'Parseoni',
          'Narkhed',
          'Umred',
          'Kuhi',
          'Bhiwapur',
          'Katol',
          'Savner',
          'Ramtek',
          'Mouda',
          'Gondia Road',
          'Wadi',
          'Khapri',
          'Bhandewadi',
          'Ajni',
        ];
      case 'Nashik':
        return [
          'Deolali',
          'Ozar',
          'Sinnar',
          'Trimbak',
          'Pimpalgaon',
          'Dindori',
          'Ghoti',
          'Lasalgaon',
          'Malegaon',
          'Niphad',
          'Igatpuri',
          'Surgana',
          'Peint',
          'Kalwan',
          'Baglan',
          'Chandwad',
          'Nandgaon',
          'Yeola',
          'Manmad',
          'Satana',
        ];
      case 'Aurangabad':
        return [
          'Paithan',
          'Gangapur',
          'Vaijapur',
          'Kannad',
          'Sillod',
          'Soegaon',
          'Phulambri',
          'Khuldabad',
          'Waluj',
          'Chikalthana',
          'Harsul',
          'Satara',
          'Garkheda',
          'Cidco',
          'Mukundwadi',
          'Padegaon',
          'Pisadevi',
          'Beed Road',
          'Gevrai',
          'Ambad',
        ];
      case 'Kolhapur':
        return [
          'Ichalkaranji',
          'Kagal',
          'Hatkanangale',
          'Shahuwadi',
          'Panhala',
          'Radhanagari',
          'Karveer',
          'Shirol',
          'Gadhinglaj',
          'Chandgad',
          'Ajra',
          'Bhudargad',
          'Gaganbawda',
          'Bavada',
          'Shivaji Park',
          'Kasaba Bawda',
          'Balinge',
          'Ujlaiwadi',
          'Gokul Shirgaon',
          'Nagaon',
        ];
      case 'Ahmednagar':
        return [
          'Shrirampur',
          'Kopargaon',
          'Sangamner',
          'Rahuri',
          'Newasa',
          'Shevgaon',
          'Pathardi',
          'Jamkhed',
          'Karjat',
          'Akole',
          'Parner',
          'Nagar',
          'Rahata',
          'Srirampur',
          'Nevasa',
          'Savedi',
          'Bhingar',
          'Kedgaon',
          'Vilad',
          'Thalner',
        ];
      case 'Satara':
        return [
          'Karad',
          'Phaltan',
          'Wai',
          'Mahabaleshwar',
          'Patan',
          'Khatav',
          'Koregaon',
          'Man',
          'Khandala',
          'Jawali',
          'Medha',
          'Mahad',
          'Umbraj',
          'Shirala',
          'Lonand',
          'Pusegaon',
          'Alore',
          'Dahiwadi',
          'Mhaswad',
          'Natepute',
        ];
      case 'Sangli-Miraj & Kupwad':
        return [
          'Miraj',
          'Kupwad',
          'Islampur',
          'Tasgaon',
          'Jat',
          'Khanapur',
          'Atpadi',
          'Walwa',
          'Shirala',
          'Kavthe Mahankal',
          'Palus',
          'Kadegaon',
          'Vita',
          'Ashta',
          'Borgaon',
          'Digraj',
          'Kundal',
          'Bedag',
          'Rajapur',
          'Visapur',
        ];
      case 'Latur':
        return [
          'Udgir',
          'Nilanga',
          'Ausa',
          'Chakur',
          'Renapur',
          'Devni',
          'Shirur Anantpal',
          'Jalkot',
          'Ahmedpur',
          'Bhokar',
          'Murud',
          'Harangul',
          'Kasarsirsi',
          'Nalgir',
          'Murudi',
          'Halga',
          'Kinhola',
          'Ghatangur',
          'Nagansur',
          'Omerga',
        ];
      case 'Nanded':
        return [
          'Dharmabad',
          'Naigaon',
          'Deglur',
          'Mudkhed',
          'Billoli',
          'Umri',
          'Loha',
          'Kinwat',
          'Hadgaon',
          'Kandhar',
          'Himayatnagar',
          'Bhokar',
          'Mahur',
          'Mukhed',
          'Ardhapur',
          'Shivajinagar',
          'Vazirabad',
          'Vishnupuri',
          'Wajegaon',
          'Sagroli',
        ];
      case 'Amravati':
        return [
          'Achalpur',
          'Chandur Bazar',
          'Daryapur',
          'Anjangaon Surji',
          'Morshi',
          'Warud',
          'Chandur Railway',
          'Dhamangaon Railway',
          'Tiosa',
          'Nandgaon Khandeshwar',
          'Chikhaldara',
          'Dharni',
          'Melghat',
          'Paratwada',
          'Bhatkuli',
          'Telhara',
          'Walgaon',
          'Badnera',
          'Murtizapur',
          'Shendurjana',
        ];
      case 'Jalgaon':
        return [
          'Bhusawal',
          'Amalner',
          'Erandol',
          'Chalisgaon',
          'Bhadgaon',
          'Pachora',
          'Jamner',
          'Raver',
          'Muktainagar',
          'Bodwad',
          'Dharangaon',
          'Parola',
          'Yawal',
          'Chopda',
          'Shirpur',
          'Savda',
          'Vaghad',
          'Mhasawad',
          'Paldhi',
          'Nimgul',
        ];
      case 'Akola':
        return [
          'Washim',
          'Akot',
          'Murtijapur',
          'Telhara',
          'Balapur',
          'Patur',
          'Murtizapur',
          'Barshitakli',
          'Mangrulpir',
          'Shegaon',
          'Malkapur',
          'Khamgaon',
          'Nandura',
          'Sangrampur',
          'Motala',
          'Paras',
          'Daryapur',
          'Hatrun',
          'Telhara',
          'Borgaon Manju',
        ];
      case 'Chandrapur':
        return [
          'Warora',
          'Chimur',
          'Bhadravati',
          'Nagbhid',
          'Sindewahi',
          'Rajura',
          'Korpana',
          'Jivti',
          'Mul',
          'Gondpipri',
          'Pombhurna',
          'Brahmapuri',
          'Saoli',
          'Ballarpur',
          'Dhanora',
          'Gadchandur',
          'Kothadi',
          'Wani',
          'Tarsa',
          'Junona',
        ];
      case 'Beed':
        return [
          'Ambajogai',
          'Kaij',
          'Parli',
          'Majalgaon',
          'Georai',
          'Shirur Kasar',
          'Ashti',
          'Patoda',
          'Wadwani',
          'Dharur',
          'Manjlegaon',
          'Banshari',
          'Rakshasbhuvan',
          'Tembhurni',
          'Pimpri Dumala',
          'Shirsala',
          'Narayan',
          'Khandewadi',
          'Pangri',
          'Pangul',
        ];
      case 'Osmanabad':
        return [
          'Tuljapur',
          'Paranda',
          'Kalamb',
          'Umarga',
          'Washi',
          'Bhoom',
          'Lohara',
          'Omerga',
          'Osmanabad City',
          'Naldurg',
          'Murud',
          'Ter',
          'Ausa',
          'Killari',
          'Khanapur',
          'Deoni',
          'Yermala',
          'Sawargaon',
          'Sarola',
          'Takli',
        ];
      case 'Wardha':
        return [
          'Hinganghat',
          'Arvi',
          'Deoli',
          'Seloo',
          'Ashti',
          'Karanja',
          'Samudrapur',
          'Pulgaon',
          'Talegaon Dashasar',
          'Aamla',
          'Nandgaon',
          'Rohana',
          'Bhidi',
          'Pandharkawda',
          'Sawangi Meghe',
          'Sindi',
          'Bori Arab',
          'Kupta',
          'Aroli',
          'Dahegaon',
        ];
      case 'Yavatmal':
        return [
          'Wani',
          'Pusad',
          'Umarkhed',
          'Mahagaon',
          'Darwha',
          'Digras',
          'Ner',
          'Ralegaon',
          'Ghatanji',
          'Kelapur',
          'Maregaon',
          'Zari Jamani',
          'Babhulgaon',
          'Pandarkawda',
          'Kalamb',
          'Murum',
          'Shirpur',
          'Deulgaon Raja',
          'Kurha',
          'Arni',
        ];
      case 'Buldhana':
        return [
          'Khamgaon',
          'Malkapur',
          'Mehkar',
          'Shegaon',
          'Chikhli',
          'Lonar',
          'Sindkhed Raja',
          'Deulgaon Raja',
          'Motala',
          'Nandura',
          'Sangrampur',
          'Jalgaon Jamod',
          'Balapur',
          'Naigaon',
          'Pimpalgaon Raja',
          'Dhad',
          'Shelgaon',
          'Dhamangaon',
          'Pipalner',
          'Kanheri Sarap',
        ];
      case 'Parbhani':
        return [
          'Selu',
          'Gangakhed',
          'Pathri',
          'Sonpeth',
          'Jintur',
          'Manwath',
          'Purna',
          'Palam',
          'Basmath',
          'Hingoli',
          'Kalamnuri',
          'Dharur',
          'Isad',
          'Pimpri Raja',
          'Vasmat',
          'Naigaon',
          'Mantha',
          'Patharwala',
          'Tadkalas',
          'Borgaon',
        ];
      case 'Ratnagiri':
        return [
          'Chiplun',
          'Khed',
          'Guhagar',
          'Mandangad',
          'Dapoli',
          'Rajapur',
          'Lanja',
          'Sangameshwar',
          'Deorukh',
          'Poladpur',
          'Harnai',
          'Jaigad',
          'Aravali',
          'Velas',
          'Anjarle',
          'Palgad',
          'Taral',
          'Burondi',
          'Nachane',
          'Mirya',
        ];
      case 'Sindhudurg':
        return [
          'Malvan',
          'Sawantwadi',
          'Kudal',
          'Vaibhavwadi',
          'Devgad',
          'Kankavli',
          'Vengurla',
          'Dodamarg',
          'Oros',
          'Banda',
          'Talye',
          'Achara',
          'Shiroda',
          'Deogad',
          'Tarkarli',
          'Vijaydurg',
          'Padel',
          'Amboli',
          'Nangal',
          'Aadeli',
        ];
      case 'Raigad':
        return [
          'Panvel',
          'Alibag',
          'Mahad',
          'Pen',
          'Mangaon',
          'Tala',
          'Murud',
          'Shrivardhan',
          'Roha',
          'Uran',
          'Khopoli',
          'Karjat',
          'Matheran',
          'Poynad',
          'Nagothane',
          'Vasheni',
          'Dhamandevi',
          'Kolad',
          'Birwadi',
          'Vadkhal',
        ];
      case 'Dhule':
        return [
          'Shirpur',
          'Sakri',
          'Sindkheda',
          'Shindkheda',
          'Dondaicha',
          'Nandurbar',
          'Shahada',
          'Navapur',
          'Taloda',
          'Akkalkuwa',
          'Dhadgaon',
          'Kopargaon',
          'Pimpalner',
          'Chinchkhede',
          'Amalner',
          'Varangaon',
          'Bhadgaon',
          'Dhule City',
          'Deopur',
          'Laling',
        ];
      case 'Gondia':
        return [
          'Tirora',
          'Amgaon',
          'Goregaon',
          'Arjuni Morgaon',
          'Deori',
          'Sadak Arjuni',
          'Salekasa',
          'Kurkheda',
          'Navegaon',
          'Itiadoh',
          'Borgaon',
          'Sausar',
          'Pipariya',
          'Bhandara',
          'Tumsar',
          'Mohadi',
          'Lakhandur',
          'Pauni',
          'Sakoli',
          'Ashti',
        ];
      case 'Gadchiroli':
        return [
          'Armori',
          'Kurkheda',
          'Dhanora',
          'Chamorshi',
          'Mulchera',
          'Bhamragad',
          'Etapalli',
          'Aheri',
          'Sironcha',
          'Wadsa',
          'Desaiganj',
          'Korchi',
          'Allapalli',
          'Chimur',
          'Gopalgaon',
          'Garchiroli',
          'Raipur',
          'Markanda',
          'Murumgaon',
          'Prabhutoli',
        ];
      case 'Bhandara':
        return [
          'Tumsar',
          'Mohadi',
          'Lakhandur',
          'Pauni',
          'Sakoli',
          'Lakhni',
          'Bagheda',
          'Nawargaon',
          'Ashti',
          'Hirdi',
          'Mundikota',
          'Mansar',
          'Shenda',
          'Khapa',
          'Ramtek',
          'Parseoni',
          'Zari',
          'Khairi',
          'Adasa',
          'Borkhedi',
        ];
      case 'Navi Mumbai':
        return [
          'Vashi',
          'Belapur',
          'Nerul',
          'Kharghar',
          'Panvel',
          'Airoli',
          'Ghansoli',
          'Koparkhairne',
          'Turbhe',
          'Sanpada',
          'Seawoods',
          'Ulwe',
          'Dronagiri',
          'Taloja',
          'Kamothe',
          'Khandeshwar',
          'Mansarovar',
          'Uran',
          'Digha',
          'Rabale',
        ];
      case 'Thane':
        return [
          'Bhiwandi',
          'Kalyan',
          'Dombivli',
          'Ambarnath',
          'Ulhasnagar',
          'Titwala',
          'Murbad',
          'Shahapur',
          'Wada',
          'Vasind',
          'Khadavli',
          'Asangaon',
          'Khardi',
          'Vangaon',
          'Atgaon',
          'Kasara',
          'Igatpuri',
          'Ghoti',
          'Navi Vasahat',
          'Padgha',
        ];

      // ── Madhya Pradesh ────────────────────────────────────────────────────────
      case 'Indore':
        return [
          'Rau',
          'Mhow',
          'Kanadia',
          'Manglia',
          'Hudco',
          'Dewas Naka',
          'Hatod',
          'Palda',
          'Sanwer',
          'Betma',
          'Depalpur',
          'Gautampura',
          'Simrol',
          'Lasudia',
          'Bicholi Mardana',
        ];
      case 'Bhopal':
        return [
          'Berasia',
          'Sehore',
          'Vidisha',
          'Raisen',
          'Mandideep',
          'Obaidullaganj',
          'Misrod',
          'Govindpura',
          'Kolar',
          'Karond',
          'Bairagarh',
          'Ratibad',
          'Phanda',
          'Budhni',
          'Ashta',
        ];

      // ── Karnataka ─────────────────────────────────────────────────────────────
      case 'Bengaluru':
        return [
          'Whitefield',
          'Yelahanka',
          'Kengeri',
          'Sarjapur',
          'Devenahalli',
          'Hosote',
          'Bidadi',
          'Nelamangala',
          'Doddaballapur',
          'Ramanagara',
          'Magadi',
          'Hoskote',
          'Attibele',
          'Chandapura',
          'Anekal',
        ];

      // ── Telangana ─────────────────────────────────────────────────────────────
      case 'Hyderabad':
        return [
          'Gachibowli',
          'Kondapur',
          'Miyapur',
          'Shamshabad',
          'Ghatkesar',
          'Hayathnagar',
          'Medchal',
          'Patancheru',
          'Dundigal',
          'Kompally',
          'Shamirpet',
          'Keesara',
          'Abdullapurmet',
          'Chevella',
          'Pargi',
        ];

      // ── Tamil Nadu ────────────────────────────────────────────────────────────
      case 'Chennai':
        return [
          'Tambaram',
          'Avadi',
          'Velachery',
          'Redhills',
          'Ambattur',
          'Sholinganallur',
          'Perumbakkam',
          'Vandalur',
          'Poonamallee',
          'Porur',
          'Thiruvottiyur',
          'Manali',
          'Madhavaram',
          'Kolathur',
          'Perambur',
        ];

      // ── West Bengal ───────────────────────────────────────────────────────────
      case 'Kolkata':
        return [
          'Rajarhat',
          'Salt Lake',
          'Barasat',
          'Sonarpur',
          'Barrackpore',
          'Madhyamgram',
          'Domjur',
          'Maheshtala',
          'Howrah',
          'Serampore',
          'Naihati',
          'Kalyani',
          'Dankuni',
          'Uluberia',
          'Rishra',
        ];

      // ── Default fallback ──────────────────────────────────────────────────────
      default:
        staticVillages = [];
    }
    if (customVillages != null) {
      final dbVillages = customVillages
          .where((v) => v.city == city)
          .map((v) => v.name as String)
          .toList();
      var combined = {...staticVillages, ...dbVillages}.toList()..sort();
      combined.remove('Others');
      combined.add('Others');
      return combined;
    }
    var result = staticVillages..sort();
    result.remove('Others');
    result.add('Others');
    return result;
  }

  static const Map<String, Map<String, String>> stateTranslations = {
    'Andaman and Nicobar Islands': {
      'mr': 'अंदमान आणि निकोबार द्वीपसमूह',
      'hi': 'अंडमान और निकोबार द्वीप समूह',
    },
    'Andhra Pradesh': {'mr': 'आंध्र प्रदेश', 'hi': 'आन्ध्र प्रदेश'},
    'Arunachal Pradesh': {'mr': 'अरुणाचल प्रदेश', 'hi': 'अरुणाचल प्रदेश'},
    'Assam': {'mr': 'आसाम', 'hi': 'असम'},
    'Bihar': {'mr': 'बिहार', 'hi': 'बिहार'},
    'Chandigarh': {'mr': 'चंदीगड', 'hi': 'चंडीगढ़'},
    'Chhattisgarh': {'mr': 'छत्तीसगड', 'hi': 'छत्तीसगढ़'},
    'Dadra and Nagar Haveli and Daman and Diu': {
      'mr': 'दादरा आणि नगर हवेली आणि दमण आणि दीव',
      'hi': 'दादरा और नगर हवेली और दमन और दीव',
    },
    'Delhi': {'mr': 'दिल्ली', 'hi': 'दिल्ली'},
    'Goa': {'mr': 'गोवा', 'hi': 'गोआ'},
    'Gujarat': {'mr': 'गुजरात', 'hi': 'गुजरात'},
    'Haryana': {'mr': 'हरियाणा', 'hi': 'हरियाणा'},
    'Himachal Pradesh': {'mr': 'हिमाचल प्रदेश', 'hi': 'हिमाचल प्रदेश'},
    'Jammu and Kashmir': {'mr': 'जम्मू आणि काश्मीर', 'hi': 'जम्मू और कश्मीर'},
    'Jharkhand': {'mr': 'झारखंड', 'hi': 'झारखण्ड'},
    'Karnataka': {'mr': 'कर्नाटक', 'hi': 'कर्नाटक'},
    'Kerala': {'mr': 'केरल', 'hi': 'केरल'},
    'Ladakh': {'mr': 'लडाख', 'hi': 'लद्दाख'},
    'Lakshadweep': {'mr': 'लक्षद्वीप', 'hi': 'लक्षद्वीप'},
    'Madhya Pradesh': {'mr': 'मध्य प्रदेश', 'hi': 'मध्य प्रदेश'},
    'Maharashtra': {'mr': 'महाराष्ट्र', 'hi': 'महाराष्ट्र'},
    'Manipur': {'mr': 'मणिपूर', 'hi': 'मणिपुर'},
    'Meghalaya': {'mr': 'मेघालय', 'hi': 'मेघालय'},
    'Mizoram': {'mr': 'मिझोराम', 'hi': 'मिज़ोरम'},
    'Nagaland': {'mr': 'नागालँड', 'hi': 'नागालैंड'},
    'Odisha': {'mr': 'ओडिशा', 'hi': 'ओडिशा'},
    'Puducherry': {'mr': 'पुडुचेरी', 'hi': 'पुडुचेरी'},
    'Punjab': {'mr': 'पंजाब', 'hi': 'पंजाब'},
    'Rajasthan': {'mr': 'राजस्थान', 'hi': 'राजस्थान'},
    'Sikkim': {'mr': 'सिक्कीम', 'hi': 'सिक्किम'},
    'Tamil Nadu': {'mr': 'तामिळनाडू', 'hi': 'तमिलनाडु'},
    'Telangana': {'mr': 'तेलंगणा', 'hi': 'तेलंगाना'},
    'Tripura': {'mr': 'त्रिपुरा', 'hi': 'त्रिपुरा'},
    'Uttar Pradesh': {'mr': 'उत्तर प्रदेश', 'hi': 'उत्तर प्रदेश'},
    'Uttarakhand': {'mr': 'उत्तराखंड', 'hi': 'उत्तराखंड'},
    'West Bengal': {'mr': 'पश्चिम बंगाल', 'hi': 'पश्चिम बंगाल'},
  };

  static const Map<String, Map<String, String>> cityTranslations = {
    // Maharashtra
    'Mumbai': {'mr': 'मुंबई', 'hi': 'मुंबई'},
    'Pune': {'mr': 'पुणे', 'hi': 'पुणे'},
    'Nagpur': {'mr': 'नागपूर', 'hi': 'नागपुर'},
    'Thane': {'mr': 'ठाणे', 'hi': 'ठाणे'},
    'Nashik': {'mr': 'नाशिक', 'hi': 'नाशिक'},
    'Pimpri-Chinchwad': {'mr': 'पिंपरी-चिंचवड', 'hi': 'पिंपरी-चिंचवड'},
    'Kalyan-Dombivli': {'mr': 'कल्याण-डोंबिवली', 'hi': 'कल्याण-डोंबिवली'},
    'Vasai-Virar': {'mr': 'वसई-विरार', 'hi': 'वसई-विरार'},
    'Aurangabad': {'mr': 'औरंगाबाद', 'hi': 'औरंगाबाद'},
    'Navi Mumbai': {'mr': 'नवी मुंबई', 'hi': 'नवी मुंबई'},
    'Solapur': {'mr': 'सोलापूर', 'hi': 'सोलापुर'},
    'Mira-Bhayandar': {'mr': 'मीरा-भाईंदर', 'hi': 'मीरा-भायंदर'},
    'Amravati': {'mr': 'अमरावती', 'hi': 'अमरावती'},
    'Akola': {'mr': 'अकोला', 'hi': 'अकोला'},
    'Bhiwandi-Nizampur': {'mr': 'भिवंडी-निजामपूर', 'hi': 'भिवंडी-निज़ामपुर'},
    'Ahmednagar': {'mr': 'अहमदनगर', 'hi': 'अहमदनगर'},
    'Jalgaon': {'mr': 'जळगाव', 'hi': 'जलगांव'},
    'Kolhapur': {'mr': 'कोल्हापूर', 'hi': 'कोल्हापुर'},
    'Sangli-Miraj & Kupwad': {
      'mr': 'सांगली-मिरज आणि कुपवाड',
      'hi': 'सांगली-मिरज और कुपवाड़',
    },
    'Malegaon': {'mr': 'मालेगाव', 'hi': 'मालेगांव'},
    'Dhule': {'mr': 'धुळे', 'hi': 'धुले'},
    'Satara': {'mr': 'सातारा', 'hi': 'सतारा'},
    'Ratnagiri': {'mr': 'रत्नागिरी', 'hi': 'रत्नागिरी'},
    'Beed': {'mr': 'बीड', 'hi': 'बीड'},
    'Chandrapur': {'mr': 'चंद्रपूर', 'hi': 'चंद्रपुर'},
    'Parbhani': {'mr': 'परभणी', 'hi': 'परभणी'},
    'Latur': {'mr': 'लातूर', 'hi': 'लातूर'},
    'Gondia': {'mr': 'गोंदिया', 'hi': 'गोंदिया'},
    'Wardha': {'mr': 'वर्धा', 'hi': 'वर्धा'},
    'Yavatmal': {'mr': 'यवतमाळ', 'hi': 'यवतमाल'},
    'Nanded': {'mr': 'नांदेड', 'hi': 'नांदेड़'},
    'Buldhana': {'mr': 'बुलढाणा', 'hi': 'बुलढाणा'},
    'Washim': {'mr': 'वाशिम', 'hi': 'वाशिम'},
    'Gadchiroli': {'mr': 'गडचिरोली', 'hi': 'गढ़चिरोली'},
    'Bhandara': {'mr': 'भंडारा', 'hi': 'भंडारा'},
    'Raigad': {'mr': 'रायगड', 'hi': 'रायगढ़'},
    'Sindhudurg': {'mr': 'सिंधुदुर्ग', 'hi': 'सिंधुदुर्ग'},
    'Osmanabad': {'mr': 'उस्मानाबाद', 'hi': 'उस्मानाबाद'},
    'Nandurbar': {'mr': 'नंदुरबार', 'hi': 'नंदुरबार'},
    'Hingoli': {'mr': 'हिंगोली', 'hi': 'हिंगोली'},

    // MP
    'Indore': {'mr': 'इंदूर', 'hi': 'इन्दौर'},
    'Bhopal': {'mr': 'भोपाळ', 'hi': 'भोपाल'},
    'Jabalpur': {'mr': 'जबलपूर', 'hi': 'जबलपुर'},
    'Gwalior': {'mr': 'ग्वाल्हेर', 'hi': 'ग्वालियर'},
    'Ujjain': {'mr': 'उज्जैन', 'hi': 'उज्जैन'},

    // Delhi
    'New Delhi': {'mr': 'नवी दिल्ली', 'hi': 'नई दिल्ली'},

    // Karnataka
    'Bengaluru': {'mr': 'बंगलोर', 'hi': 'बेंगलुरु'},

    // Telangana
    'Hyderabad': {'mr': 'हैदराबाद', 'hi': 'हैदराबाद'},
  };

  static const Map<String, Map<String, String>> villageTranslations = {
    // ── Solapur ──────────────────────────────────────────────────────────────
    'Pandharpur': {'mr': 'पंढरपूर', 'hi': 'पंढरपुर'},
    'Bandishegaon': {'mr': 'भंडीशेगाव', 'hi': 'भंडीशेगाव'},
    'Shelve': {'mr': 'शेळवे', 'hi': 'शेल्वे'},
    'Kuroli': {'mr': 'कुरोली', 'hi': 'कुरोली'},
    'Dhondewadi': {'mr': 'धोंडेवाडी', 'hi': 'धोंडेवाडी'},
    'Upari': {'mr': 'उपरी', 'hi': 'उपरी'},
    'Mangalwedha': {'mr': 'मंगळवेढा', 'hi': 'मंगलवेढा'},
    'Akkalkot': {'mr': 'अक्कलकोट', 'hi': 'अक्कलकोट'},
    'Barshi': {'mr': 'बार्शी', 'hi': 'बार्शी'},
    'Mohol': {'mr': 'मोहोळ', 'hi': 'मोहोल'},
    'Karmala': {'mr': 'करमाळा', 'hi': 'कर्माला'},
    'Madha': {'mr': 'माढा', 'hi': 'माढा'},
    'Sangola': {'mr': 'सांगोला', 'hi': 'सांगोला'},
    'Malshiras': {'mr': 'माळशिरस', 'hi': 'मालशिरस'},
    'Akluj': {'mr': 'अकलूज', 'hi': 'अकलूज'},
    'Natepute': {'mr': 'नातेपुते', 'hi': 'नातेपुते'},
    'Vairag': {'mr': 'वैराग', 'hi': 'वैराग'},
    'Velapur': {'mr': 'वेळापूर', 'hi': 'वेलापुर'},
    'Kegaon': {'mr': 'केगाव', 'hi': 'केगांव'},
    'Hotgi': {'mr': 'होटगी', 'hi': 'होटगी'},
    'Nannaj': {'mr': 'नान्नज', 'hi': 'नान्नज'},
    'Bhalwani': {'mr': 'भालवणी', 'hi': 'भालवनी'},
    'Wadala': {'mr': 'वडाळा', 'hi': 'वडाला'},
    'Chincholi': {'mr': 'चिंचोली', 'hi': 'चिंचोली'},
    'Dound': {'mr': 'दौंड', 'hi': 'दौंड'},
    'Narayanpur': {'mr': 'नारायणपूर', 'hi': 'नारायणपुर'},
    'Angar': {'mr': 'अंगार', 'hi': 'अंगार'},
    'Kasegaon': {'mr': 'कासेगाव', 'hi': 'कासेगांव'},
    'Borampuri': {'mr': 'बोरामपुरी', 'hi': 'बोरामपुरी'},
    'Shegaon': {'mr': 'शेगाव', 'hi': 'शेगांव'},

    // ── Akola ─────────────────────────────────────────────────────────────
    'Akot': {'mr': 'अकोट', 'hi': 'अकोट'},
    'Balapur': {'mr': 'बाळापूर', 'hi': 'बालापुर'},
    'Murtizapur': {'mr': 'मूर्तीजापूर', 'hi': 'मूर्तिजापुर'},
    'Patur': {'mr': 'पातूर', 'hi': 'पातूर'},
    'Telhara': {'mr': 'तेल्हारा', 'hi': 'तेल्हारा'},
    'Barshitakli': {'mr': 'बार्शीटाकळी', 'hi': 'बार्शीटाकळी'},

    // ── Buldhana ──────────────────────────────────────────────────────────
    'Khamgaon': {'mr': 'खामगाव', 'hi': 'खामगांव'},
    'Chikhli': {'mr': 'चिखली', 'hi': 'चिखली'},
    'Deulgaon Raja': {'mr': 'देऊळगाव राजा', 'hi': 'देउलगांव राजा'},
    'Malkapur': {'mr': 'मलकापूर', 'hi': 'मलकापुर'},
    'Mehkar': {'mr': 'मेहकर', 'hi': 'मेहकर'},
    'Motala': {'mr': 'मोताळा', 'hi': 'मोताला'},
    'Nandura': {'mr': 'नांदुरा', 'hi': 'नांदुरा'},
    'Sindkhed Raja': {'mr': 'सिंदखेड राजा', 'hi': 'सिंदखेड़ राजा'},
    'Lonar': {'mr': 'लोणार', 'hi': 'लोणार'},
    'Sangrampur': {'mr': 'संग्रामपूर', 'hi': 'संग्रामपुर'},

    // ── Pune ─────────────────────────────────────────────────────────────────
    'Wagholi': {'mr': 'वाघोली', 'hi': 'वाघोली'},
    'Hinjawadi': {'mr': 'हिंजवडी', 'hi': 'हिंजवडी'},
    'Ambegaon': {'mr': 'आंबेगाव', 'hi': 'आंबेगांव'},
    'Manjri': {'mr': 'मांजरी', 'hi': 'मांजरी'},
    'Mulshi': {'mr': 'मुळशी', 'hi': 'मुळशी'},
    'Hadapsar': {'mr': 'हडपसर', 'hi': 'हडपसर'},
    'Koregaon Bhima': {'mr': 'कोरेगाव भीमा', 'hi': 'कोरेगांव भीमा'},
    'Chakan': {'mr': 'चाकण', 'hi': 'चाकण'},
    'Loni Kalbhor': {'mr': 'लोणी काळभोर', 'hi': 'लोणी कालभोर'},
    'Pirangut': {'mr': 'पिरंगुट', 'hi': 'पिरंगुट'},
    'Shirur': {'mr': 'शिरूर', 'hi': 'शिरूर'},
    'Indapur': {'mr': 'इंदापूर', 'hi': 'इंदापुर'},
    'Baramati': {'mr': 'बारामती', 'hi': 'बारामती'},
    'Daund': {'mr': 'दौंड', 'hi': 'दौंड'},
    'Junnar': {'mr': 'जुन्नर', 'hi': 'जुन्नर'},
    'Khed': {'mr': 'खेड', 'hi': 'खेड'},
    'Maval': {'mr': 'मावळ', 'hi': 'मावल'},
    'Purandar': {'mr': 'पुरंदर', 'hi': 'पुरंदर'},
    'Velhe': {'mr': 'वेल्हे', 'hi': 'वेल्हे'},
    'Bhor': {'mr': 'भोर', 'hi': 'भोर'},
    'Uruli Kanchan': {'mr': 'उरुळी कांचन', 'hi': 'उरुली कांचन'},
    'Shikrapur': {'mr': 'शिक्रापूर', 'hi': 'शिक्रापुर'},
    'Nighoje': {'mr': 'निघोजे', 'hi': 'निघोजे'},
    'Talegaon Dabhade': {'mr': 'तळेगाव दाभाडे', 'hi': 'तालेगांव दाभाडे'},
    'Rajgurunagar': {'mr': 'राजगुरुनगर', 'hi': 'राजगुरुनगर'},

    // ── Mumbai ────────────────────────────────────────────────────────────────
    'Gorai': {'mr': 'गोराई', 'hi': 'गोराई'},
    'Versova': {'mr': 'वर्सोवा', 'hi': 'वर्सोवा'},
    'Madh': {'mr': 'मढ', 'hi': 'मढ'},
    'Manori': {'mr': 'मनोरी', 'hi': 'मनोरी'},
    'Marve': {'mr': 'मार्वे', 'hi': 'मार्वे'},
    'Dharavi': {'mr': 'धारावी', 'hi': 'धारावी'},
    'Kanjurmarg': {'mr': 'कांजूरमार्ग', 'hi': 'कांजूरमार्ग'},
    'Bhandup': {'mr': 'भांडुप', 'hi': 'भांडुप'},
    'Ghatkopar': {'mr': 'घाटकोपर', 'hi': 'घाटकोपर'},
    'Vikhroli': {'mr': 'विक्रोळी', 'hi': 'विक्रोली'},
    'Mulund': {'mr': 'मुलुंड', 'hi': 'मुलुंड'},
    'Powai': {'mr': 'पवई', 'hi': 'पवई'},
    'Kurla': {'mr': 'कुर्ला', 'hi': 'कुर्ला'},
    'Chembur': {'mr': 'चेंबूर', 'hi': 'चेंबूर'},
    'Govandi': {'mr': 'गोवंडी', 'hi': 'गोवंडी'},
    'Trombay': {'mr': 'ट्रॉम्बे', 'hi': 'ट्रॉम्बे'},
    'Colaba': {'mr': 'कुलाबा', 'hi': 'कुलाबा'},
    'Worli': {'mr': 'वरळी', 'hi': 'वर्ली'},
    'Matunga': {'mr': 'माटुंगा', 'hi': 'माटुंगा'},
    'Sion': {'mr': 'शीव', 'hi': 'शीव'},

    // ── Nagpur ────────────────────────────────────────────────────────────────
    'Kamptee': {'mr': 'कामठी', 'hi': 'कामठी'},
    'Hingna': {'mr': 'हिंगणा', 'hi': 'हिंगणा'},
    'Kalmeshwar': {'mr': 'कळमेश्वर', 'hi': 'कलमेश्वर'},
    'Butibori': {'mr': 'बुटीबोरी', 'hi': 'बुटीबोरी'},
    'Wanadongri': {'mr': 'वाणडोंगरी', 'hi': 'वाणडोंगरी'},
    'Bori': {'mr': 'बोरी', 'hi': 'बोरी'},
    'Parseoni': {'mr': 'पारशिवनी', 'hi': 'पारशिवनी'},
    'Narkhed': {'mr': 'नरखेड', 'hi': 'नरखेड'},
    'Umred': {'mr': 'उमरेड', 'hi': 'उमरेड'},
    'Kuhi': {'mr': 'कुही', 'hi': 'कुही'},
    'Bhiwapur': {'mr': 'भिवापूर', 'hi': 'भिवापुर'},
    'Katol': {'mr': 'काटोल', 'hi': 'काटोल'},
    'Savner': {'mr': 'सावनेर', 'hi': 'सावनेर'},
    'Ramtek': {'mr': 'रामटेक', 'hi': 'रामटेक'},
    'Mouda': {'mr': 'मौदा', 'hi': 'मौदा'},
    'Wadi': {'mr': 'वाडी', 'hi': 'वाडी'},
    'Khapri': {'mr': 'खापरी', 'hi': 'खापरी'},
    'Ajni': {'mr': 'अजनी', 'hi': 'अजनी'},

    // ── Nashik ────────────────────────────────────────────────────────────────
    'Deolali': {'mr': 'देवळाली', 'hi': 'देवलाली'},
    'Ozar': {'mr': 'ओझर', 'hi': 'ओझर'},
    'Sinnar': {'mr': 'सिन्नर', 'hi': 'सिन्नर'},
    'Trimbak': {'mr': 'त्र्यंबक', 'hi': 'त्र्यंबक'},
    'Pimpalgaon': {'mr': 'पिंपळगाव', 'hi': 'पिंपळगाव'},
    'Dindori': {'mr': 'दिंडोरी', 'hi': 'दिंडोरी'},
    'Ghoti': {'mr': 'घोती', 'hi': 'घोती'},
    'Lasalgaon': {'mr': 'लासलगाव', 'hi': 'लासलगांव'},
    'Niphad': {'mr': 'निफाड', 'hi': 'निफाड'},
    'Igatpuri': {'mr': 'इगतपुरी', 'hi': 'इगतपुरी'},
    'Surgana': {'mr': 'सुरगाणा', 'hi': 'सुरगाणा'},
    'Kalwan': {'mr': 'कळवण', 'hi': 'कलवण'},
    'Chandwad': {'mr': 'चांदवड', 'hi': 'चांदवड'},
    'Nandgaon': {'mr': 'नांदगाव', 'hi': 'नांदगांव'},
    'Yeola': {'mr': 'येवला', 'hi': 'येवला'},
    'Manmad': {'mr': 'मनमाड', 'hi': 'मनमाड'},
    'Satana': {'mr': 'सटाणा', 'hi': 'सटाणा'},

    // ── Aurangabad ────────────────────────────────────────────────────────────
    'Paithan': {'mr': 'पैठण', 'hi': 'पैठण'},
    'Gangapur': {'mr': 'गंगापूर', 'hi': 'गंगापुर'},
    'Vaijapur': {'mr': 'वैजापूर', 'hi': 'वैजापुर'},
    'Kannad': {'mr': 'कन्नड', 'hi': 'कन्नड'},
    'Sillod': {'mr': 'सिल्लोड', 'hi': 'सिल्लोड'},
    'Phulambri': {'mr': 'फुलंब्री', 'hi': 'फुलंब्री'},
    'Khuldabad': {'mr': 'खुलताबाद', 'hi': 'खुलताबाद'},
    'Waluj': {'mr': 'वाळूज', 'hi': 'वालुज'},
    'Gevrai': {'mr': 'गेवराई', 'hi': 'गेवराई'},
    'Ambad': {'mr': 'अंबड', 'hi': 'अंबड'},

    // ── Kolhapur ──────────────────────────────────────────────────────────────
    'Ichalkaranji': {'mr': 'इचलकरंजी', 'hi': 'इचलकरंजी'},
    'Kagal': {'mr': 'कागल', 'hi': 'कागल'},
    'Hatkanangale': {'mr': 'हातकणंगले', 'hi': 'हातकणंगले'},
    'Shahuwadi': {'mr': 'शाहूवाडी', 'hi': 'शाहूवाडी'},
    'Panhala': {'mr': 'पन्हाळा', 'hi': 'पन्हाला'},
    'Radhanagari': {'mr': 'राधानगरी', 'hi': 'राधानगरी'},
    'Shirol': {'mr': 'शिरोळ', 'hi': 'शिरोल'},
    'Gadhinglaj': {'mr': 'गडहिंग्लज', 'hi': 'गडहिंगलज'},
    'Chandgad': {'mr': 'चंदगड', 'hi': 'चंदगड'},
    'Ajra': {'mr': 'आजरा', 'hi': 'आजरा'},

    // ── Satara ────────────────────────────────────────────────────────────────
    'Karad': {'mr': 'कराड', 'hi': 'कराड'},
    'Phaltan': {'mr': 'फलटण', 'hi': 'फलटण'},
    'Wai': {'mr': 'वाई', 'hi': 'वाई'},
    'Mahabaleshwar': {'mr': 'महाबळेश्वर', 'hi': 'महाबलेश्वर'},
    'Patan': {'mr': 'पाटण', 'hi': 'पाटण'},
    'Koregaon': {'mr': 'कोरेगाव', 'hi': 'कोरेगांव'},
    'Khandala': {'mr': 'खंडाळा', 'hi': 'खंडाला'},

    // ── Ahmednagar ────────────────────────────────────────────────────────────
    'Shrirampur': {'mr': 'श्रीरामपूर', 'hi': 'श्रीरामपुर'},
    'Kopargaon': {'mr': 'कोपरगाव', 'hi': 'कोपरगांव'},
    'Sangamner': {'mr': 'संगमनेर', 'hi': 'संगमनेर'},
    'Rahuri': {'mr': 'राहुरी', 'hi': 'राहुरी'},
    'Shevgaon': {'mr': 'शेवगाव', 'hi': 'शेवगांव'},
    'Jamkhed': {'mr': 'जामखेड', 'hi': 'जामखेड'},
    'Akole': {'mr': 'अकोले', 'hi': 'अकोले'},
    'Parner': {'mr': 'पारनेर', 'hi': 'पारनेर'},

    // ── Latur ─────────────────────────────────────────────────────────────────
    'Udgir': {'mr': 'उदगीर', 'hi': 'उदगीर'},
    'Nilanga': {'mr': 'निलंगा', 'hi': 'निलंगा'},
    'Ausa': {'mr': 'औसा', 'hi': 'औसा'},
    'Chakur': {'mr': 'चाकूर', 'hi': 'चाकूर'},
    'Renapur': {'mr': 'रेणापूर', 'hi': 'रेणापुर'},
    'Ahmedpur': {'mr': 'अहमदपूर', 'hi': 'अहमदपुर'},
    'Omerga': {'mr': 'उमरगा', 'hi': 'उमरगा'},

    // ── Nanded ────────────────────────────────────────────────────────────────
    'Dharmabad': {'mr': 'धर्माबाद', 'hi': 'धर्माबाद'},
    'Deglur': {'mr': 'देगलूर', 'hi': 'देगलूर'},
    'Mudkhed': {'mr': 'मुदखेड', 'hi': 'मुदखेड'},
    'Billoli': {'mr': 'बिलोली', 'hi': 'बिलोली'},
    'Loha': {'mr': 'लोहा', 'hi': 'लोहा'},
    'Kinwat': {'mr': 'किनवट', 'hi': 'किनवट'},
    'Hadgaon': {'mr': 'हदगाव', 'hi': 'हदगांव'},
    'Kandhar': {'mr': 'कंधार', 'hi': 'कंधार'},
    'Mukhed': {'mr': 'मुखेड', 'hi': 'मुखेड'},
    'Mahur': {'mr': 'माहूर', 'hi': 'माहूर'},

    // ── Amravati ──────────────────────────────────────────────────────────────
    'Achalpur': {'mr': 'अचलपूर', 'hi': 'अचलपुर'},
    'Daryapur': {'mr': 'दर्यापूर', 'hi': 'दर्यापुर'},
    'Morshi': {'mr': 'मोर्शी', 'hi': 'मोर्शी'},
    'Warud': {'mr': 'वरूड', 'hi': 'वरूड'},
    'Chikhaldara': {'mr': 'चिखलदरा', 'hi': 'चिखलदरा'},
    'Paratwada': {'mr': 'परतवाडा', 'hi': 'परतवाडा'},
    'Badnera': {'mr': 'बडनेरा', 'hi': 'बडनेरा'},

    // ── Jalgaon ───────────────────────────────────────────────────────────────
    'Bhusawal': {'mr': 'भुसावळ', 'hi': 'भुसावल'},
    'Amalner': {'mr': 'अमळनेर', 'hi': 'अमलनेर'},
    'Erandol': {'mr': 'एरंडोल', 'hi': 'एरंडोल'},
    'Chalisgaon': {'mr': 'चाळीसगाव', 'hi': 'चालीसगांव'},
    'Pachora': {'mr': 'पाचोरा', 'hi': 'पाचोरा'},
    'Jamner': {'mr': 'जामनेर', 'hi': 'जामनेर'},
    'Raver': {'mr': 'रावेर', 'hi': 'रावेर'},
    'Bodwad': {'mr': 'बोदवड', 'hi': 'बोदवड'},
    'Chopda': {'mr': 'चोपडा', 'hi': 'चोपडा'},
    'Shirpur': {'mr': 'शिरपूर', 'hi': 'शिरपुर'},

    // ── Wardha ────────────────────────────────────────────────────────────────
    'Hinganghat': {'mr': 'हिंगणघाट', 'hi': 'हिंगनघाट'},
    'Arvi': {'mr': 'आर्वी', 'hi': 'आर्वी'},
    'Deoli': {'mr': 'देवळी', 'hi': 'देवली'},
    'Karanja': {'mr': 'कारंजा', 'hi': 'कारंजा'},
    'Samudrapur': {'mr': 'समुद्रपूर', 'hi': 'समुद्रपुर'},
    'Pulgaon': {'mr': 'पुलगाव', 'hi': 'पुलगांव'},

    // ── Yavatmal ──────────────────────────────────────────────────────────────
    'Wani': {'mr': 'वणी', 'hi': 'वणी'},
    'Pusad': {'mr': 'पुसद', 'hi': 'पुसद'},
    'Umarkhed': {'mr': 'उमरखेड', 'hi': 'उमरखेड'},
    'Darwha': {'mr': 'दारव्हा', 'hi': 'दारवहा'},
    'Digras': {'mr': 'दिग्रस', 'hi': 'दिग्रस'},
    'Ghatanji': {'mr': 'घाटंजी', 'hi': 'घाटंजी'},

    // ── Chandrapur ────────────────────────────────────────────────────────────
    'Warora': {'mr': 'वरोरा', 'hi': 'वरोरा'},
    'Chimur': {'mr': 'चिमूर', 'hi': 'चिमूर'},
    'Bhadravati': {'mr': 'भद्रावती', 'hi': 'भद्रावती'},
    'Nagbhid': {'mr': 'नागभीड', 'hi': 'नागभीड'},
    'Rajura': {'mr': 'राजुरा', 'hi': 'राजुरा'},
    'Brahmapuri': {'mr': 'ब्रम्हपुरी', 'hi': 'ब्रह्मपुरी'},
    'Ballarpur': {'mr': 'बल्लारपूर', 'hi': 'बल्लारपुर'},

    // ── Beed ──────────────────────────────────────────────────────────────────
    'Ambajogai': {'mr': 'अंबाजोगाई', 'hi': 'अंबाजोगाई'},
    'Kaij': {'mr': 'काईज', 'hi': 'काईज'},
    'Parli': {'mr': 'परळी', 'hi': 'परली'},
    'Majalgaon': {'mr': 'माजलगाव', 'hi': 'माजलगांव'},
    'Georai': {'mr': 'गेवराई', 'hi': 'गेवराई'},
    'Ashti': {'mr': 'आष्टी', 'hi': 'आष्टी'},

    // ── Osmanabad ─────────────────────────────────────────────────────────────
    'Tuljapur': {'mr': 'तुळजापूर', 'hi': 'तुलजापुर'},
    'Paranda': {'mr': 'परांडा', 'hi': 'परांडा'},
    'Kalamb': {'mr': 'कळंब', 'hi': 'कलंब'},
    'Umarga': {'mr': 'उमरगा', 'hi': 'उमरगा'},
    'Bhoom': {'mr': 'भूम', 'hi': 'भूम'},
    'Naldurg': {'mr': 'नळदुर्ग', 'hi': 'नलदुर्ग'},
    'Killari': {'mr': 'किल्लारी', 'hi': 'किल्लारी'},

    // ── Ratnagiri ─────────────────────────────────────────────────────────────
    'Chiplun': {'mr': 'चिपळूण', 'hi': 'चिपलून'},
    'Guhagar': {'mr': 'गुहागर', 'hi': 'गुहागर'},
    'Dapoli': {'mr': 'दापोली', 'hi': 'दापोली'},
    'Rajapur': {'mr': 'राजापूर', 'hi': 'राजापुर'},
    'Lanja': {'mr': 'लांजा', 'hi': 'लांजा'},
    'Harnai': {'mr': 'हर्णे', 'hi': 'हर्णे'},
    'Tarkarli': {'mr': 'तारकर्ली', 'hi': 'तारकर्ली'},

    // ── Sindhudurg ────────────────────────────────────────────────────────────
    'Malvan': {'mr': 'मालवण', 'hi': 'मालवण'},
    'Sawantwadi': {'mr': 'सावंतवाडी', 'hi': 'सावंतवाडी'},
    'Kudal': {'mr': 'कुडाळ', 'hi': 'कुडाळ'},
    'Devgad': {'mr': 'देवगड', 'hi': 'देवगड'},
    'Kankavli': {'mr': 'कणकवली', 'hi': 'कणकवली'},
    'Vengurla': {'mr': 'वेंगुर्ला', 'hi': 'वेंगुर्ला'},
    'Vijaydurg': {'mr': 'विजयदुर्ग', 'hi': 'विजयदुर्ग'},
    'Amboli': {'mr': 'आंबोली', 'hi': 'आंबोली'},

    // ── Raigad ────────────────────────────────────────────────────────────────
    'Panvel': {'mr': 'पनवेल', 'hi': 'पनवेल'},
    'Alibag': {'mr': 'अलिबाग', 'hi': 'अलिबाग'},
    'Mahad': {'mr': 'महाड', 'hi': 'महाड'},
    'Pen': {'mr': 'पेण', 'hi': 'पेण'},
    'Mangaon': {'mr': 'माणगाव', 'hi': 'मांगांव'},
    'Murud': {'mr': 'मुरुड', 'hi': 'मुरुड'},
    'Shrivardhan': {'mr': 'श्रीवर्धन', 'hi': 'श्रीवर्धन'},
    'Roha': {'mr': 'रोहा', 'hi': 'रोहा'},
    'Uran': {'mr': 'उरण', 'hi': 'उरण'},
    'Khopoli': {'mr': 'खोपोली', 'hi': 'खोपोली'},
    'Karjat': {'mr': 'कर्जत', 'hi': 'कर्जत'},
    'Matheran': {'mr': 'माथेरान', 'hi': 'माथेरान'},
    'Kolad': {'mr': 'कोलाड', 'hi': 'कोलाड'},

    // ── Navi Mumbai ───────────────────────────────────────────────────────────
    'Vashi': {'mr': 'वाशी', 'hi': 'वाशी'},
    'Belapur': {'mr': 'बेलापूर', 'hi': 'बेलापुर'},
    'Nerul': {'mr': 'नेरुळ', 'hi': 'नेरुल'},
    'Kharghar': {'mr': 'खारघर', 'hi': 'खारघर'},
    'Airoli': {'mr': 'ऐरोली', 'hi': 'ऐरोली'},
    'Ghansoli': {'mr': 'घणसोली', 'hi': 'घणसोली'},
    'Koparkhairne': {'mr': 'कोपरखैरणे', 'hi': 'कोपरखैरणे'},
    'Turbhe': {'mr': 'तुर्भे', 'hi': 'तुर्भे'},
    'Sanpada': {'mr': 'सानपाडा', 'hi': 'सानपाडा'},
    'Seawoods': {'mr': 'सीवुड्स', 'hi': 'सीवुड्स'},
    'Ulwe': {'mr': 'उलवे', 'hi': 'उलवे'},
    'Taloja': {'mr': 'तळोजा', 'hi': 'तालोजा'},
    'Kamothe': {'mr': 'कामोठे', 'hi': 'कामोठे'},
    'Rabale': {'mr': 'रबाळे', 'hi': 'रबाले'},

    // ── Thane ─────────────────────────────────────────────────────────────────
    'Bhiwandi': {'mr': 'भिवंडी', 'hi': 'भिवंडी'},
    'Kalyan': {'mr': 'कल्याण', 'hi': 'कल्याण'},
    'Dombivli': {'mr': 'डोंबिवली', 'hi': 'डोंबिवली'},
    'Ambarnath': {'mr': 'अंबरनाथ', 'hi': 'अंबरनाथ'},
    'Ulhasnagar': {'mr': 'उल्हासनगर', 'hi': 'उल्हासनगर'},
    'Titwala': {'mr': 'टिटवाळा', 'hi': 'टिटवाला'},
    'Murbad': {'mr': 'मुरबाड', 'hi': 'मुरबाड'},
    'Shahapur': {'mr': 'शहापूर', 'hi': 'शाहपुर'},
    'Wada': {'mr': 'वाडा', 'hi': 'वाडा'},
    'Vasind': {'mr': 'वासिंद', 'hi': 'वासिंद'},
    'Kasara': {'mr': 'कसारा', 'hi': 'कसारा'},
    'Padgha': {'mr': 'पडघा', 'hi': 'पडघा'},

    // ── Indore ────────────────────────────────────────────────────────────────
    'Rau': {'mr': 'राऊ', 'hi': 'राऊ'},
    'Mhow': {'mr': 'महू', 'hi': 'महू'},
    'Kanadia': {'mr': 'कनाडिया', 'hi': 'कनाडिया'},
    'Manglia': {'mr': 'मांगलिया', 'hi': 'मांगलिया'},
    'Hudco': {'mr': 'हुडको', 'hi': 'हुडको'},
    'Dewas Naka': {'mr': 'देवास नाका', 'hi': 'देवास नाका'},
    'Hatod': {'mr': 'हातोद', 'hi': 'हातोद'},
    'Palda': {'mr': 'पालदा', 'hi': 'पालदा'},

    // ── Bengaluru ─────────────────────────────────────────────────────────────
    'Whitefield': {'mr': 'व्हाईटफील्ड', 'hi': 'व्हाइटफील्ड'},
    'Yelahanka': {'mr': 'येळहंका', 'hi': 'येलाहंका'},
    'Kengeri': {'mr': 'केंगेरी', 'hi': 'केंगेरी'},
    'Sarjapur': {'mr': 'सर्जापूर', 'hi': 'सरजापुर'},
    'Devenahalli': {'mr': 'देवनाहल्ली', 'hi': 'देवनाहल्ली'},
    'Hosote': {'mr': 'होसोत', 'hi': 'होसोत'},
    'Bidadi': {'mr': 'बिदाडी', 'hi': 'बिदाड़ी'},
    'Nelamangala': {'mr': 'नेलमंगला', 'hi': 'नेलमंगला'},
    'Doddaballapur': {'mr': 'दोड्डाबल्लापूर', 'hi': 'दोड्डाबल्लापुर'},
    'Ramanagara': {'mr': 'रामनगर', 'hi': 'रामनगर'},
    'Hoskote': {'mr': 'होसकोटे', 'hi': 'होसकोटे'},
    'Anekal': {'mr': 'अनेकल', 'hi': 'अनेकल'},

    // ── Hyderabad ─────────────────────────────────────────────────────────────
    'Gachibowli': {'mr': 'गचीबावली', 'hi': 'गचीबावली'},
    'Kondapur': {'mr': 'कोंडापूर', 'hi': 'कोंडापुर'},
    'Miyapur': {'mr': 'मियापूर', 'hi': 'मियापुर'},
    'Shamshabad': {'mr': 'शमशाबाद', 'hi': 'शमशाबाद'},
    'Ghatkesar': {'mr': 'घाटकेसर', 'hi': 'घाटकेसर'},
    'Hayathnagar': {'mr': 'हयात नगर', 'hi': 'हयात नगर'},
    'Medchal': {'mr': 'मेदचल', 'hi': 'मेदचल'},
    'Patancheru': {'mr': 'पटानचेरु', 'hi': 'पटानचेरु'},
    'Kompally': {'mr': 'कोम्पल्ली', 'hi': 'कोम्पल्ली'},
    'Shamirpet': {'mr': 'शामीरपेट', 'hi': 'शामीरपेट'},

    // ── Chennai ───────────────────────────────────────────────────────────────
    'Tambaram': {'mr': 'तांबरम', 'hi': 'तांबरम'},
    'Avadi': {'mr': 'आवडी', 'hi': 'आवडी'},
    'Velachery': {'mr': 'वेलाचेरी', 'hi': 'वेलाचेरी'},
    'Redhills': {'mr': 'रेडहिल्स', 'hi': 'रेडहिल्स'},
    'Ambattur': {'mr': 'अंबत्तूर', 'hi': 'अंबत्तूर'},
    'Sholinganallur': {'mr': 'शोलिंगनाल्लूर', 'hi': 'शोलिंगनाल्लूर'},
    'Perumbakkam': {'mr': 'पेरुमबक्कम', 'hi': 'पेरुमबक्कम'},
    'Vandalur': {'mr': 'वंडलूर', 'hi': 'वंडलूर'},
    'Poonamallee': {'mr': 'पूनामल्ली', 'hi': 'पूनामल्ली'},
    'Porur': {'mr': 'पोरूर', 'hi': 'पोरूर'},

    // ── Kolkata ───────────────────────────────────────────────────────────────
    'Rajarhat': {'mr': 'राजारहाट', 'hi': 'राजारहाट'},
    'Salt Lake': {'mr': 'सॉल्ट लेक', 'hi': 'सॉल्ट लेक'},
    'Barasat': {'mr': 'बारासात', 'hi': 'बारासात'},
    'Sonarpur': {'mr': 'सोनारपूर', 'hi': 'सोनारपुर'},
    'Barrackpore': {'mr': 'बॅरकपूर', 'hi': 'बैरकपुर'},
    'Madhyamgram': {'mr': 'मध्यमग्राम', 'hi': 'मध्यमग्राम'},
    'Domjur': {'mr': 'डोमजूर', 'hi': 'डोमजूर'},
    'Maheshtala': {'mr': 'महेशतला', 'hi': 'महेशतला'},
    'Serampore': {'mr': 'सेरामपोर', 'hi': 'सेरामपोर'},
    'Naihati': {'mr': 'नईहाटी', 'hi': 'नईहाटी'},
    'Kalyani': {'mr': 'कल्याणी', 'hi': 'कल्याणी'},
    'Uluberia': {'mr': 'उलुबेरिया', 'hi': 'उलुबेरिया'},

    // ── Fallbacks ─────────────────────────────────────────────────────────────
    'Rampur': {'mr': 'रामपूर', 'hi': 'रामपुर'},
    'Mohanpur': {'mr': 'मोहनपूर', 'hi': 'मोहनपुर'},
    'Kalyanpur': {'mr': 'कल्याणपूर', 'hi': 'कल्याणपुर'},
    'Siddhpur': {'mr': 'सिद्धपूर', 'hi': 'सिद्धपुर'},
    'Hariharpur': {'mr': 'हरीहरपूर', 'hi': 'हरीहरपुर'},
    'Gopalpur': {'mr': 'गोपाळपूर', 'hi': 'गोपालपुर'},
    'Fatehpur': {'mr': 'फत्तेपूर', 'hi': 'फतेहपुर'},
    'Anandpur': {'mr': 'आनंदपूर', 'hi': 'आनंदपुर'},
    'Chandpur': {'mr': 'चांदपूर', 'hi': 'चांदपुर'},
    'Jitpur': {'mr': 'जीतपूर', 'hi': 'जीतपुर'},
  };

  static String getLocalizedStateName(String state, String langCode) {
    if (langCode == 'mr') {
      return stateTranslations[state]?['mr'] ?? state;
    } else if (langCode == 'hi') {
      return stateTranslations[state]?['hi'] ?? state;
    }
    return state;
  }

  static String getLocalizedCityName(String city, String langCode, {List<dynamic>? customCities}) {
    if (customCities != null) {
      for (final c in customCities) {
        if (c.name == city) {
          if (langCode == 'mr') return c.nameMr ?? c.name;
          if (langCode == 'hi') return c.nameHi ?? c.name;
          return c.name;
        }
      }
    }
    if (langCode == 'mr') {
      return cityTranslations[city]?['mr'] ?? city;
    } else if (langCode == 'hi') {
      return cityTranslations[city]?['hi'] ?? city;
    }
    return city;
  }

  static String getLocalizedVillageName(String village, String langCode, {List<dynamic>? customVillages}) {
    if (customVillages != null) {
      for (final v in customVillages) {
        if (v.name == village) {
          if (langCode == 'mr') return v.nameMr ?? v.name;
          if (langCode == 'hi') return v.nameHi ?? v.name;
          return v.name;
        }
      }
    }
    if (langCode == 'mr') {
      return villageTranslations[village]?['mr'] ?? village;
    } else if (langCode == 'hi') {
      return villageTranslations[village]?['hi'] ?? village;
    }
    return village;
  }
}
